version: 2

project_name: git-sync-status

before:
  hooks:
    - go mod tidy

builds:
  - id: git-sync-status
    main: ./cmd/git-sync-status
    binary: git-sync-status
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt

changelog:
  use: git
